# 1. Write a python Function to list even and odd numbers in a list.

In [42]:
def evod_no(n):
    even = []
    odd = []
    for num in n:
        if num % 2 == 0:
            even.append(num)
        else:
            odd.append(num)
    return even, odd
numlist = [3,6,9,12,15,18,21,24,27]
e, o = evod_no(numlist)
print("Even numbers:", e)
print("Odd numbers:", o)


Even numbers: [6, 12, 18, 24]
Odd numbers: [3, 9, 15, 21, 27]


# 2. Write and run a Python program that asks the user to enter 8 integers (one at a time), and then

prints out how many of those integers were even numbers. For example, if the user entered 19,

6, 9, 20, 13, 7, 6, and 1, then your program should print out 3 since 3 of those numbers were

even.

In [64]:
count = 0
for i in range(8):
    try:
        user_input = int(input("Enter integer:"))
        if user_input % 2 == 0:
            count += 1
    except ValueError:
        print(" not an integer.")
print("Out of the 8 integers entered", count," of them are even.")


Enter integer:1
Enter integer:2
Enter integer:3
Enter integer:4
Enter integer:5
Enter integer:6
Enter integer:7
Enter integer:8
Out of the 8 integers entered 4  of them are even.


# 3. Write a Python program where you take any positive integer n, if n is even, divide it by 2 to get n /2. If n is odd, multiply it by 3 and add 1 to obtain 3n + 1. Repeat the process until you reach 1.

In [11]:
def seq(n):
    nseq = [n]
    if n < 1:
       return []
    while n > 1:
       if n % 2 == 0:
         n = n / 2
       else:
         n = 3 * n + 1
       nseq.append(n)    
    return nseq
n=int(input("enter any positive int:"))
print(seq(n))

enter any positive int:15
[15, 46, 23.0, 70.0, 35.0, 106.0, 53.0, 160.0, 80.0, 40.0, 20.0, 10.0, 5.0, 16.0, 8.0, 4.0, 2.0, 1.0]


# 4. Write a Python program to compute the sum of all the multiples of 3 or 5 below 500.

In [1]:
sum = 0
for i in range(1,500):
     if i % 5==0 or i % 3==0:
         sum = sum + i
print("sum of multiples of 3 or 5 below 500 is:",sum)

sum of multiples of 3 or 5 below 500 is: 57918


# 5. To write a Python program to find first 'n' prime numbers from a list of given numbers.

In [2]:
def prime(n):
    if n<=1: 
        return False
    for i in range(2,n):
        if(n%i==0):
            return False
        else:
            return True
lst = [1,2,8,55,15,3, 5,30, 7, 25, 13, 17, 19, 29, 33, 37, 41, 43, 47, 51, 55, 62]
prime_nums = []
num = 1
n = int(input("Enter a number:"))
while len(prime_nums) < n: 
    if num in lst and prime (num):
            prime_nums.append(num)
    num += 1
print("Prime numbers: ", prime_nums)

Enter a number:5
Prime numbers:  [3, 5, 7, 13, 15]


# 6. To write a Python program to compute matrix multiplication.

In [11]:
import numpy as np
i=[[2,3,4],[3,5,6],[4,5,3]]
j=[[1,2,1],[-1,2,1],[3,2,1]]
r=np.dot(i,j)
print(r)

[[11 18  9]
 [16 28 14]
 [ 8 24 12]]


# 7. Write a python Function to count the number of vowels in a string.

In [18]:
Str = input('Enter the string :')
count = 0
Str = Str.lower()
for i in Str:
    if i == 'a' or i == 'e' or i == 'i' or i == 'o' or i == 'u':
        count+=1
if count == 0:
    print('No vowels found')
else:
    print('Total vowels are :', count)

Enter the string :bhargavi
Total vowels are : 3


# 8. Write a python Function for finding factorial for the given number using a recursive function.

In [21]:
def frec(n):
    if n == 0:  
        return 1
    else:
        return n * frec(n - 1)
n=int(input("enter a number:"))
r = frec(n)
print("The factorial of", n,"is", r)


enter a number:6
The factorial of 6 is 720


# 9. Write a python Function for generating the Fibonacci series using the function.

In [5]:
def fib(n):
    a,b=0,1
    fib_series=[] 
    for i in range(n):
        fib_series.append(a) 
        a,b=b,a+b 
    return fib_series
n=int(input('enter a num: ')) 
print('finonacci series: ', fib(n))

enter a num: 5
finonacci series:  [0, 1, 1, 2, 3]


# 10. Python program to display the given integer in reverse order using the function without an in- built

function.

In [35]:
def revno(n):
    if n < 10:
        return n
    else:
        ld= n % 10
        rem = n // 10
        rev = revno(rem)
        return int(str(ld) + str(rev))
 
number = int(input("Enter a number: "))
rev = revno(number)
print("Reversed number:", rev)

Enter a number: 123456789
Reversed number: 987654321


# 11. Write a Python Function to display all integers within the range 200-300 whose sum of digits is an

even number.

In [12]:
def evensum():
    for i in range(200,300):
        s=0
        for j in str(i):
            s+=int(j)
        if s%2==0:
                print(i,end=" ")
evensum()


200 202 204 206 208 211 213 215 217 219 220 222 224 226 228 231 233 235 237 239 240 242 244 246 248 251 253 255 257 259 260 262 264 266 268 271 273 275 277 279 280 282 284 286 288 291 293 295 297 299 

# 12. Write a python Function to find the number of digits and sum of digits for a giveninteger.

In [63]:
def count_and_sum(number):
    digits = 0
    dsum = 0
    while number > 0:
        d = number % 10
        digits += 1
        dsum += d
        number //= 10
    return digits, dsum

n = int(input("enter a number:"))
count, sum = count_and_sum(n)
print("Number of digits in", n,":", count)
print("Sum of digits in",n,":", sum)

enter a number:963
Number of digits in 963 : 3
Sum of digits in 963 : 18


# 13. Write functions called is _sorted that takes a list as a parameter and returns True if the list is sorted

in ascending order and False otherwise and has_ duplicates that takes a list and returns True if

there is any element that appears more than once. It should not modify the original list.

In [5]:
def is_sort(l):
    return l==sorted(l)
def dup(l):
    return len(l)!=len(set(l))
lst=[6,7,8,9,10,12,12,22]
print("is list sorted?",is_sort(lst))
print("any duplicate values?",dup(lst))

is list sorted? True
any duplicate values? True


# 14. Write functions called nested_sum that takes a list of integers and adds up the elements from all

the nested lists and cumsum that takes a list of numbers and returns the cumulative sum; that is, a

new list where the ith element is the sum of the first i + 1 elements from the original list.

In [8]:
def n(l):
    t = 0
    for item in l:
        if isinstance(item, list):
            t += nest(item)
        else:
            t += item
    return t
nlist = [2, 3, [6, 18], [10, [12, 14]]]
result = n(nlist)
print("Sum of elements in nested list:",result)
def cumsum(numbers):
    cumulative_sum = []
    current_sum = 0
    for num in numbers:
        current_sum += num
        cumulative_sum.append(current_sum)
    return cumulative_sum
my_list = [1,2,3,4,5,6]
cumulative_result = cumsum(my_list)
print("Cumulative sum of the list:", cumulative_result)

Sum of elements in nested list: 65
Cumulative sum of the list: [1, 3, 6, 10, 15, 21]
